version: '3.8'
services:
  app:
    image: 'docker-customer:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - node-network
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: testdb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge