#server:
#  port: 1453
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      username: test
      password: test
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo
      port: 27017
      database: testdb
      username: test
      password: test
      authentication-database: admin